# 基本イメージとしてPythonの公式イメージを使用
FROM python:3.8

# 作業ディレクトリを設定
ARG project_dir=/api_server/

ADD ./requirements.txt $project_dir

WORKDIR $project_dir

RUN pip install -r requirements.txt


# PYTHONPATH の設定
ENV PYTHONPATH=/api_server

CMD ["python", "app.py"]