FROM node:18

WORKDIR /app/

# package.jsonとpackage-lock.jsonをコピーして依存関係をインストール
COPY ./next/package*.json /app/



# 追加のパッケージをインストール
RUN npm install react-hook-form@7.49.3 react-router-dom@6.21.2
#RUN npm install -g firebase-tools \
 #   && npm install react-hook-form@7.49.3 react-router-dom@6.21.2

RUN npm install

# 残りのファイルをコピー
COPY ./next /app/


# 開発サーバーを起動
CMD ["npm", "run", "dev"]

