# 基本イメージとしてPythonの公式イメージを使用
FROM python:3.8

# 作業ディレクトリを設定
WORKDIR /app

#ENV FLASK_APP=api
#ENV FLASK_ENV=development

COPY api_server/requirements.txt ./api_server/

RUN pip install --no-cache-dir -r api_server/requirements.txt

# ポート5000を公開（Flaskのデフォルトポート）
EXPOSE 5000

# コンテナ起動時に実行されるコマンド
CMD ["python", "/app/api_server/app.py"]
