version: '3.8'
services:
  flask:
    container_name: flask-python
    build: 
      context: ../
      dockerfile: docker/Dockerfile.api_server
    ports:
      - 5000:5000
    links:
      - mysql
    privileged: true
    volumes:
      - ../api_server:/api_server
    tty: true
    environment:
        TZ: Asia/Tokyo
        FLASK_ENV: 'development'    #デバッグモードON
        FLASK_APP: 'app.py'         #起動用アプリの設定
    command: flask run -h 0.0.0.0
       #  depends_on:
       #     - db
       
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.next
    env_file:
      - ../.env
    volumes:
      - ../next:/app/next
    ports:
      - "3000:3000" 
  
  mysql:
    container_name: mysql-db
    image: mysql:5.7    #Mac対応の為変更
    platform: linux/x86_64 #Mac対応の為変更
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: templete
      MYSQL_USER: hoge
      MYSQL_PASSWORD: huga
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306