version: '3.8'
services:
  api_server:
    build:
      context: ../
      dockerfile:  docker/Dockerfile.api_server
    env_file:
      - ../.env
    volumes:
      - ../api_server:/app/api_server
    ports:
      - "5000:5000"
 #  depends_on:
  #     - db
#
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.next
    env_file:
      - ../.env
    volumes:
      - ../next:/app/next
    ports:
      - "3000:3000"