"""empty message

Revision ID: 49d23bc23bac
Revises: d7d49a2343f6
Create Date: 2024-02-04 13:35:53.638822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d23bc23bac'
down_revision = 'd7d49a2343f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HealthInformation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senior_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'SeniorUser', ['senior_user_id'], ['senior_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HealthInformation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('senior_user_id')

    # ### end Alembic commands ###
