"""empty message

Revision ID: 648801bc1727
Revises: 
Create Date: 2024-02-05 00:32:55.346366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648801bc1727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HealthInformation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'SeniorUser', ['senior_user_id'], ['senior_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HealthInformation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
