"""empty message

Revision ID: d7d49a2343f6
Revises: 
Create Date: 2024-01-30 15:49:03.606720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d49a2343f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FamilyUser',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('family_last_name', sa.String(length=255), nullable=False),
    sa.Column('family_first_name', sa.String(length=255), nullable=False),
    sa.Column('relationship_with_senior', sa.String(length=255), nullable=False),
    sa.Column('family_email', sa.String(length=255), nullable=False),
    sa.Column('family_tel', sa.String(length=255), nullable=False),
    sa.Column('family_password', sa.String(length=255), nullable=True),
    sa.Column('family_uid', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('family_id'),
    sa.UniqueConstraint('family_uid')
    )
    op.create_table('HealthInformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('good', 'normal', 'bad'), nullable=False),
    sa.Column('symptom', sa.Enum('head', 'face', 'neck', 'shoulder', 'chest', 'rightArm', 'leftArm', 'leftHand', 'rightHand', 'abdomen', 'rightLeg', 'leftLeg', 'leftAnkle', 'rightAnkle', 'back', 'buttocks'), nullable=False),
    sa.Column('medicine', sa.Boolean(), nullable=False),
    sa.Column('dinner_photo', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.Enum('full', 'half', 'less'), nullable=True),
    sa.Column('voice_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SeniorUser',
    sa.Column('senior_user_id', sa.Integer(), nullable=False),
    sa.Column('senior_last_name', sa.String(length=255), nullable=False),
    sa.Column('senior_first_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('senior_email', sa.String(length=255), nullable=False),
    sa.Column('senior_tel', sa.String(length=255), nullable=False),
    sa.Column('health_status', sa.String(length=255), nullable=False),
    sa.Column('medication', sa.Boolean(), nullable=False),
    sa.Column('medication_frequency', sa.String(length=255), nullable=False),
    sa.Column('senior_user_uid', sa.String(length=191), nullable=True),
    sa.Column('senior_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('senior_user_id'),
    sa.UniqueConstraint('senior_user_uid')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('SeniorUser')
    op.drop_table('HealthInformation')
    op.drop_table('FamilyUser')
    # ### end Alembic commands ###
